source /sharefs/hbkg/user/luoqi/home/scan_MEfit_env.sh;sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/ME/ME_SCAN/ME_SCAN/lcfit/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/ME/Prod/P030124063101/config_me_small.xml
source /sharefs/hbkg/user/luoqi/home/scan_MEfit_env.sh;sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/ME/ME_SCAN/lcfit/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/ME/Prod/P030124063101/config_me_small.xml
source /sharefs/hbkg/user/luoqi/home/scan_MEfit_env.sh;sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/ME/ME_SCAN/lcfit/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/ME/Prod/P010129500103/config_me_small.xml
source /sharefs/hbkg/user/luoqi/home/scan_MEfit_env.sh;sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/ME/ME_SCAN/lcfit/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/ME/Prod/P030124062201/config_me_small.xml
source /sharefs/hbkg/user/luoqi/home/scan_MEfit_env.sh;sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/ME/ME_SCAN/lcfit/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/ME/Prod/P030124061901/config_me_small.xml
source /sharefs/hbkg/user/luoqi/home/scan_MEfit_env.sh;sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/ME/ME_SCAN/lcfit/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/ME/Prod/P030124062101/config_me_small.xml
source /sharefs/hbkg/user/luoqi/home/scan_MEfit_env.sh;sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/ME/ME_SCAN/lcfit/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/ME/Prod/P030124062001/config_me_small.xml
source /sharefs/hbkg/user/luoqi/home/scan_MEfit_env.sh;sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/ME/ME_SCAN/lcfit/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/ME/Prod/P030124062501/config_me_small.xml
source /sharefs/hbkg/user/luoqi/home/scan_MEfit_env.sh;sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/ME/ME_SCAN/lcfit/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/ME/Prod/P030124062601/config_me_small.xml
source /sharefs/hbkg/user/luoqi/home/scan_MEfit_env.sh;sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/ME/ME_SCAN/lcfit/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/ME/Prod/P030124062301/config_me_small.xml
source /sharefs/hbkg/user/luoqi/home/scan_MEfit_env.sh;sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/ME/ME_SCAN/lcfit/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/ME/Prod/P030124062401/config_me_small.xml
source /sharefs/hbkg/user/luoqi/home/scan_MEfit_env.sh;sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/ME/ME_SCAN/lcfit/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/ME/Prod/P030124062701/config_me_small.xml
source /sharefs/hbkg/user/luoqi/home/scan_MEfit_env.sh;sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/ME/ME_SCAN/lcfit/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/ME/Prod/P030124063201/config_me_small.xml
source /sharefs/hbkg/user/luoqi/home/scan_MEfit_env.sh;sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/ME/ME_SCAN/lcfit/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/ME/Prod/P030124063101/config_me_small.xml
source /sharefs/hbkg/user/luoqi/home/scan_MEfit_env.sh;sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/ME/ME_SCAN/lcfit/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/ME/Prod/P030124062901/config_me_small.xml
source /sharefs/hbkg/user/luoqi/home/scan_MEfit_env.sh;sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/ME/ME_SCAN/lcfit/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/ME/Prod/P030124063001/config_me_small.xml
source /sharefs/hbkg/user/luoqi/home/scan_MEfit_env.sh;sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/ME/ME_SCAN/lcfit/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/ME/Prod/P030124062801/config_me_small.xml
source /sharefs/hbkg/user/luoqi/home/scan_MEfit_env.sh;sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/ME/ME_SCAN/lcfit/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/ME/Prod/P030124063401/config_me_small.xml
source /sharefs/hbkg/user/luoqi/home/scan_MEfit_env.sh;sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/ME/ME_SCAN/lcfit/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/ME/Prod/P030124063301/config_me_small.xml
source /sharefs/hbkg/user/luoqi/home/scan_MEfit_env.sh;sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/ME/ME_SCAN/lcfit/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/ME/Prod/P030124063501/config_me_small.xml
source /sharefs/hbkg/user/luoqi/home/scan_MEfit_env.sh;sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/ME/ME_SCAN/lcfit/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/ME/Prod/P030124063601/config_me_small.xml
source /sharefs/hbkg/user/luoqi/home/scan_MEfit_env.sh;sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/ME/ME_SCAN/lcfit/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/ME/Prod/P030124063801/config_me_small.xml
source /sharefs/hbkg/user/luoqi/home/scan_MEfit_env.sh;sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/ME/ME_SCAN/lcfit/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/ME/Prod/P030124063701/config_me_small.xml
source /sharefs/hbkg/user/luoqi/home/scan_MEfit_env.sh;sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/ME/ME_SCAN/lcfit/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/ME/Midd/P030124062901/config_me_small.xml
source /sharefs/hbkg/user/luoqi/home/scan_MEfit_env.sh;sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/ME/ME_SCAN/lcfit/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/ME/Midd/P030124062901/config_me_small.xml
source /sharefs/hbkg/user/luoqi/home/scan_MEfit_env.sh;sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/ME/ME_SCAN/lcfit/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/ME/Midd/P030124000501/config_me_small.xml
source /sharefs/hbkg/user/luoqi/home/scan_MEfit_env.sh;sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/ME/ME_SCAN/lcfit/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/ME/Midd/P030124060101/config_me_small.xml
source /sharefs/hbkg/user/luoqi/home/scan_MEfit_env.sh;sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/ME/ME_SCAN/lcfit/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/ME/Midd/P010129506101/config_me_small.xml
source /sharefs/hbkg/user/luoqi/home/scan_MEfit_env.sh;sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/ME/ME_SCAN/lcfit/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/ME/Midd/P030124064101/config_me_small.xml
source /sharefs/hbkg/user/luoqi/home/scan_MEfit_env.sh;sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/ME/ME_SCAN/lcfit/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/ME/Midd/P030124064201/config_me_small.xml
source /sharefs/hbkg/user/luoqi/home/scan_MEfit_env.sh;sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/ME/ME_SCAN/lcfit/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/ME/Midd/P030124064601/config_me_small.xml
source /sharefs/hbkg/user/luoqi/home/scan_MEfit_env.sh;sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/ME/ME_SCAN/lcfit/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/ME/Midd/P030124064701/config_me_small.xml
source /sharefs/hbkg/user/luoqi/home/scan_MEfit_env.sh;sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/ME/ME_SCAN/lcfit/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/ME/Midd/P030124064501/config_me_small.xml
source /sharefs/hbkg/user/luoqi/home/scan_MEfit_env.sh;sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/ME/ME_SCAN/lcfit/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/ME/Midd/P030124064401/config_me_small.xml
source /sharefs/hbkg/user/luoqi/home/scan_MEfit_env.sh;sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/ME/ME_SCAN/lcfit/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/ME/Midd/P030124064301/config_me_small.xml
source /sharefs/hbkg/user/luoqi/home/scan_MEfit_env.sh;sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/ME/ME_SCAN/lcfit/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/ME/Midd/P030124065101/config_me_small.xml
source /sharefs/hbkg/user/luoqi/home/scan_MEfit_env.sh;sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/ME/ME_SCAN/lcfit/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/ME/Midd/P030124064901/config_me_small.xml
source /sharefs/hbkg/user/luoqi/home/scan_MEfit_env.sh;sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/ME/ME_SCAN/lcfit/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/ME/Midd/P030124064801/config_me_small.xml
source /sharefs/hbkg/user/luoqi/home/scan_MEfit_env.sh;sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/ME/ME_SCAN/lcfit/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/ME/Midd/P030124065001/config_me_small.xml
source /sharefs/hbkg/user/luoqi/home/scan_MEfit_env.sh;sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/ME/ME_SCAN/lcfit/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/ME/Midd/P030124065201/config_me_small.xml
