sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124000501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124000201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124000601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124000701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124000801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124001001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124001101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124001201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124001501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124001601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124001701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124001801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124002101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124002201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124002401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124002301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124002501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124002601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124002701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124003001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124003101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124003301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124003401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124003801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124003601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124003701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124004101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124004201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124004301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124004601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124004901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124005001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124005201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124005101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124006201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124005801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124006101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124005501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124005601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124005701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124006701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124006401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124006601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124007001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124007301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124006901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124007801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124007901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124007401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124007501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124007601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124008301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124008101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124008001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124008801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124008601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124008701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124008901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124009001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124010101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124009701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124009501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124009101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124009801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124009601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124010001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124009901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124010401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124010201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124010501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124010601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124010701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124011101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124010801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124011201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124011801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124011001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124011601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124011901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124011501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124012101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124012001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124011401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124011301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124012201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124012401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124012901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124012501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124012601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124014001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124012301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124013601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124013301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124013801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124013001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124013501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124013701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124013101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124014301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124014201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124014101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124013401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124013201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124015001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124013901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124014801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124015101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124016001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124014601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124016101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124015601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124014901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124015401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124015501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124014701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124016201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124015301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124015701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124016401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124017301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124017001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124016301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124017101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124016801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124017601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124016601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124017201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124018201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124017401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124016701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124016901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124018001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124017801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124017701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124018501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124017501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124018401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124019201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124019001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124018301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124018701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124020001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124018101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124019501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124018901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124019701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124018801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124019101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124019601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124019901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124018601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124019801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124020101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124020301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124020401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124020801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124020201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124021101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124020701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124021201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124021301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124021401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124022201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124021001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124021901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124020901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124022501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124023201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124021701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124022401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124022601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124022101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124022701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124022001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124023601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124024301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124023301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124023001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124023101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124023401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124024201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124023501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124023701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124024401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124024801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124024101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124023901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124025001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124023801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124024601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124024701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124024901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124024501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124025101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124025701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124025301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124025501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124027201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124026301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124026201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124025901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124025601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124026401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124025201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124026001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124025801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124026901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124026101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124026801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124027101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124027501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124028201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124028101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124027701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124027601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124027401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124028301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124028701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124027301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124027801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124028601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124028801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124029001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124029301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124028401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124029601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124029101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124028901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124030301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124030201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124029701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124029801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124030001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124029501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124029901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124030401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124030101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124030701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124030901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124031201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124031901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124031701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124031501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124031601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124030501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124031301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124032101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124031801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124032201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124032001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124031401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124032601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124033201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124032701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124032501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124033701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124033101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124033301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124032901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124032801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124033401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124033001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124033501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124034501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124033901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124034001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124034401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124034601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124035001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124034301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124035201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124034801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124034101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124034201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124035301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124035701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124035501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124036601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124034701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124035901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124036101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124035601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124035801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124036401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124036001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124036201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124035401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124036701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124036801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124036901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124037001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124037501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124037401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124037601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124037901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124038101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124038001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124037701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124037301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124038501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124039001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124038601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124038401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124038701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124039601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124038901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124039701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124039501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124037801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124039401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124039101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124039901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124040201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124039301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124040301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124040601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124040101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124040001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124041301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124041501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124041201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124041401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124041101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124040501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124041701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124041801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124042101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124042501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124040701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124042301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124042001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124042701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124042401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124041901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124043101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124043301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124040901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124043001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124043601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124043701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124042601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124043501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124044601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124044501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124043801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124044801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124045001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124044301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124044901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124044401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124043201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124045301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124044101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124045401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124044201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124046201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124045101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124046101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124046001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124045901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124047201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124045601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124046501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124046801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124046901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124045701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124047301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124046401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124047001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124045801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124047901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124047401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124048901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124047501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124047601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124050201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124049901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124049701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124050701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124051801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124050501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124048201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124050901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124051601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124051501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124051001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124051701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124052101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124053601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124052401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124050401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124053501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124051301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124053201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124052701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124053001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124053101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124052501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124052001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124054501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124052601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124053701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124055101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124054801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124055301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124056301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124055401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124054201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124055601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124056201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124056701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124056001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124056801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124056101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124057501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124057801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124057001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124056901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124057901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124058101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124057401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124056601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124057201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124057301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124058601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124058501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124055701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124059001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124058701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124058301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124058001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124057101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124059101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124058201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124058401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124059601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124059301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124059701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124060501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124060401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124059201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124060201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124061301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124061801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124060601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124061401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124060701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124060801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124061201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124061701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124061601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124061101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124062101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124062001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124022201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124023601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124062001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124022201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124029601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124023601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124062001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124040901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124022201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124029601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124023601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124030901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124025501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124032001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124062001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124040901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124023601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124028201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124025501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124030901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124029601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124032001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124062001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124040901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124022201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Prod/P030124017201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124063801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124063701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124063801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124063601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124063901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124064001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124064101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124000501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P010129506101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124068001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124064401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124066101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124068001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124066301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124064401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124064301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124068801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124066101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124067301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124068001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124066301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124068801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124066101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124067301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124066001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124068701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124065301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124064401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124064301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124065801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124068001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124066301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124067701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124068801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124067301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124066101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124068701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124066501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124066001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124065301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124064401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124064301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124065901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124065801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124064201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124068001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124067401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124068801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124067701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124066301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124067301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124068701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124066901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124066101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124066001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124066501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124065301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124064401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124064301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124065901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124065801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124064201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124068001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124068801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124067701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124067401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124068701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124067301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124067001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124066301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124066601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124066501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124066901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124066101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124065301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124066001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124065901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124064401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124064801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124065801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124064301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124063501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124064201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124068001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124067901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124068801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124067401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124067701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124068701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124067301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124067001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124066301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P010129506101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124067801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124066301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124067901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124064501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124068801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124065001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124068701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124065501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124066901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124065301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124067401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124066601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124066401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124064701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124067101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124068201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124066701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124067701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124068301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124064201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124067601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124063401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124065801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124063501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124064601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/GRB/Midd/P030124066101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124064801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P010129506101/config_he.xml
