sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124000501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124000601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124000701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124000801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124003301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124003401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124006201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124006701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124006601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124007801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124007901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124008101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124008001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124010101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124009701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124009501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124009801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124009601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124010001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124009901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124010201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124011801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124011901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124012101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124012001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124012201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124013801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124022201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124021901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124022101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124022001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124023901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124025301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124029301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124030701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124033701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124035001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124036401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124038701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124039601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124039701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124039501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124039401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124039301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124042101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124043301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124040901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124043701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124044601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124043801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124045101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124047201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124047301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124050201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124049701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124050701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124051001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124051301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124022201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124022201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124040901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124022201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124040901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124040901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124022201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124063801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124063701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124063801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124063601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124063901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124064001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P030124064101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124000501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Prod/P010129506101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P010129506101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124068001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124064401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124068001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124064401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124064301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124068001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124065301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124064401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124064301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124068001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124067701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124065301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124064401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124064301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124064201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124068001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124067701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124065301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124064401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124064301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124064201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124068001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124067701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124065301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124064401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124064801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124064301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124063501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124064201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124068001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124067901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124067701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P010129506101/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124067801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124067901/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124064501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124065001/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124065501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124065301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124064701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124068201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124067701/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124068301/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124064201/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124067601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124063401/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124063501/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124064601/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/sub_gps_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P030124064801/config_he.xml
sh /sharefs/hbkg/user/luoqi/HXMT_SCAN/HE/HXMT_GPS_Program/task_lcfit.sh /sharefs/hbkg/data/SCAN/HE/Midd/P010129506101/config_he.xml
